## Student Performance Indicator

### Life Cycle Of Machine Learning Project

- Understanding problem statement
- Data collection
- Data checks to perform
- Exploratory data analysis
- Data pre processing
- Model Training
- Choose best model

### Problem Statement
- This project understands how the student's performance(test scores) is affected by other variables such as Gender, Ethnicity, Parental level of education, Lunch and Test prepration score.

### Data Collection
- Dataset source- https://www.kaggle.com/datasets/spscientist/students-performance-in-exams?datasetId=74977
- The dataset consists of 8 columns and 1000 rows.

### importing important libaries

In [1]:
import numpy as np 
import pandas as pd 
import warnings
import seaborn as sns
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

### Import the csv data as pandas dataframe

In [2]:
df=pd.read_csv("study.csv")

### Show top five records

In [3]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

### Shape of the dataset

In [20]:
df.shape

(1000, 8)

### Dataset information
- gender: sex of students (Male or Female)
- race/ethnicity: ethnicity of students(Group A,B,C,D,E)
- parental level of education: parents's final education(bachelor degree,high school,associate degree,some colleage,master degree)
- lunch: having lunch before test(standard, free/reduced)
- test prepration course: complete or not complete before test
- math score
- reading score
- writing score

### Data checks to perform
- check missing values
- check duplicate values
- check datatype
- check the number of unique values of every column
- check statistics of dataset
- check various categories of present different categorical columns

In [21]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

### check for duplicate values

In [18]:
df.duplicated().sum()

0

### check for missing values

In [17]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

### check datatype

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

### check the number of unique values in each columns

In [4]:
df.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

### check statistics of dataset

In [23]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### insights from data
- From above descriptive of numerical data, all means are very close to eachother between 66.0 to 68.0
- All standard deviation are also very close to eachother between 14 and 15.19
- Minimum value for math score is 0, for writing score it is little higher 10 and for reading score it is 17 much higher.

### Exploring data

In [3]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
print("Categories in 'gender' variable:     ",end=" " )
print(df['gender'].unique())

print("Categories in 'race_ethnicity' variable:  ",end=" ")
print(df['race/ethnicity'].unique())

print("Categories in'parental level of education' variable:",end=" " )
print(df['parental level of education'].unique())

print("Categories in 'lunch' variable:     ",end=" " )
print(df['lunch'].unique())

print("Categories in 'test preparation course' variable:     ",end=" " )
print(df['test preparation course'].unique())

Categories in 'gender' variable:      ['female' 'male']
Categories in 'race_ethnicity' variable:   ['group B' 'group C' 'group A' 'group D' 'group E']
Categories in'parental level of education' variable: ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
Categories in 'lunch' variable:      ['standard' 'free/reduced']
Categories in 'test preparation course' variable:      ['none' 'completed']

In [10]:
### define numerical and categorical columns
numeric_feature=[feature for feature in df.columns if df[feature].dtype!='O']
categorical_feature=[feature for feature in df.columns if df[feature].dtype=="O"]

print('we have {} feature in {}'.format(len(numeric_feature),numeric_feature))
print('we have {} features in {}'.format(len(categorical_feature),categorical_feature))

we have 3 feature in ['math score', 'reading score', 'writing score']
we have 5 features in ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

### Adding the value for total score and average

In [12]:
df['total_score']=df['math score']+df['reading score']+df['writing score']
df['average']=df['total_score']/3
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333

In [15]:
df[df['reading score']==50]['average']

182    49.000000
227    53.666667
262    48.333333
511    52.333333
834    51.000000
948    50.333333
972    54.333333
Name: average, dtype: float64

In [18]:
df['reading score']==50

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: reading score, Length: 1000, dtype: bool